Update README and presubmit script.

diff --git a/scripts/presubmit b/scripts/presubmit
--- a/scripts/presubmit
+++ b/scripts/presubmit
@@ -1,4 +1,10 @@
-#!/bin/bash -ex
+#!/bin/bash -e
+
+function check_readme() {
+    perl -0777 -pe 's/.*## '"$3"'\n\n```rust\n(.*)```.*/$1/s' $1 \
+        | colordiff $2 - \
+        || { printf "\n${RED}ERROR${RESET}: $3 in $1 differs from $1.\n"; exit 1; }
+}
 
 cd "$(dirname "$0")/.."
 
@@ -8,16 +14,13 @@ GREEN="$(tput setaf 2)"
 RESET="$(tput sgr0)"
 
 cargo fmt -- --check \
-    || { echo "\n${RED}ERROR${RESET}: Must run \`cargo fmt\` before submitting."; exit 1; }
+    || { printf "\n${RED}ERROR${RESET}: Must run \`cargo fmt\` before submitting.\n"; exit 1; }
 
 cargo test
 
+check_readme README.md tempdb_cockroach/tests/usage.rs "Example usage"
 for crate in tempdb_cockroach; do
-    pushd $crate
-    perl -0777 -pe 's/.*## Usage\n\n```rust\n(.*)```.*/$1/s' README.md \
-        | colordiff tests/usage.rs - \
-        || { echo "\n${RED}ERROR${RESET}: Usage in $package/README.md differs from $package/tests/usage.rs."; exit 1; }
-    popd
+    check_readme $crate/README.md $crate/tests/usage.rs "Usage"
 done
 
-printf "Presubmits ${GREEN}PASSED${RESET}.\n\n"
+printf "\nPresubmits ${GREEN}PASSED${RESET}.\n"
